### ISSUE TITLE
Optional Chaining Operator not supported in Node LTS

### ISSUE THREAD

**Issue by drewcovi** [jvmahon/homebridge-hubitat#18]
Can we please revert Optional Chaining Operator in the latest releases? The Homebridge image for raspberry pi and various other platforms leverages the LTS Node release, and this update broke the install and cleared the device cache.

**Comment by jvmahon** [comment]
Didn't realize this was so new.  Removed in 1.0..8.

**Comment by drewcovi** [comment]
No worries, sir. I updated my pi and now the CLI for the Ozonu services realizes there's a new LTS release... I usually want to keep my devices up to date, but this breaking change definitely means ill be spending a few hours replacing my devices ;)

**Comment by jvmahon** [comment]
I had the same problem (having to put all devices back into their rooms) after updating to homebridge 1.3.1 -- so it may have been the homebridge update -- did you also do that update at the same time?  Since I had to re-assign devices to rooms anyway, I wiped out the 'persist' and 'accessories' directory to do a fresh start, and also use the new homebridge 1.3.1 child bridge feature to set up different plugins in different child bridges.

**Comment by drewcovi** [comment]
Did the update to Homebridge awhile back, just various plugins this time so probably not related. I'm on my way for now... unfortunately HomeKit doesn't have an easy way to do backups (a few apps now like Home+ allow backup/restore although in beta, and it sorta failed me). Anyways, sounds like you've been here, and know the grind. I can support those operations now, but hopefully ive taken arrows to the other poor souls stuck in node 12 land :)

**Comment by jvmahon** [comment]
Thanks!  Use of thermostats is pretty rare, but hopefully, backing out the ?. operator will prevent others from crashing.
